NAVER_CLIENT_ID='o58Yv2p1v5JR4CrzUhWe'
NAVER_CLIENT_SECRET='FoHO0xQQlN'
CLOVA_API_KEY='NTA0MjU2MWZlZTcxNDJiYw2CZOs8LhY/wBUCKhM9FkoAlQR/CKopjC/H+Z1ylwiY'
CLOVA_API_KEY_PRIMARY_VAL='HJI48MZFS1LaIvExbGJ0qutqdURMSTvEHhqHuikz'
CLOVA_REQUEST_ID='6b72935d47ef4a8abfa15962b09394e1'